### ISSUE TITLE
install does not work for rabbitmq 3.10.x

### ISSUE THREAD

**Issue by narrowtux** [w-sanches/asdf-rabbitmq#2]
Since the install script checks for the version [naively](https://github.com/w-sanches/asdf-rabbitmq/blob/master/bin/install#L24), it tries to download a .gz file for versions from 3.10 onward, which results in this error: 
```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
mv: cannot stat '/tmp/tmp.p8u7IdoHVb/rabbitmq_server-3.10.6/*': No such file or directory
```

**Comment by mjcc30** [comment]
Same probleme for me i have to install the latest version before 3.10.0

asdf install rabbitmq 3.9.22
